export const SET_PRODUCT_AUDIT_LIST = "productAudit/SET_PRODUCT_AUDIT_LIST"
export const SET_PRODUCT_AUDIT_DETAIL = "productAudit/SET_PRODUCT_AUDIT_DETAIL"
export const SET_PRODUCT_AUDIT_STATUS = "productAudit/SET_PRODUCT_AUDIT_STATUS"
export const CLEAR_PRODUCT_INFO = 'product/CLEAR_PRODUCT_INFO'
export const TRIGGER_LOADING = 'productAudit/TRIGGER_LOADING'